config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/create',   to: 'products#new'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :products,          only: [:create, :edit, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :reviews,            only: [:create, :destroy]
  resources :products do
     resources :reviews
 end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  has_many :products, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                foreign_key: "follower_id",
                                dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                 foreign_key: "followed_id",
                                 dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :firstname, presence: true, length: { maximum: 50 }
  validates :lastname, presence: true, length: { maximum: 50 }
  validates :contactnum, presence: true, length: { maximum: 40 }
  validates :address, presence: true, length: { maximum: 100 }
  validates :zipcode, presence: true, length: { maximum: 6 }
  validates :country, presence: true, length: { maximum: 60 }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
end

  def self.new_token
    SecureRandom.urlsafe_base64
   end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
end

def authenticated?(attribute, token)
   digest = send("#{attribute}_digest")
   return false if digest.nil?
   BCrypt::Password.new(digest).is_password?(token)
 end

  def forget
  update_attribute(:remember_digest, nil)
  end

  # Activates an account.
def activate
  update_attribute(:activated,    true)
  update_attribute(:activated_at, Time.zone.now)
end

# Sends activation email.
def send_activation_email
  UserMailer.account_activation(self).deliver_now
end

# Sets the password reset attributes.
def create_reset_digest
  self.reset_token = User.new_token
  update_attribute(:reset_digest,  User.digest(reset_token))
  update_attribute(:reset_sent_at, Time.zone.now)
end

# Sends password reset email.
def send_password_reset_email
  UserMailer.password_reset(self).deliver_now
end

# Returns true if a password reset has expired.
def password_reset_expired?
  reset_sent_at < 2.hours.ago
end

# Returns a user's status feed.
def feed
  following_ids = "SELECT followed_id FROM relationships
                   WHERE  follower_id = :user_id"
  Product.where("user_id IN (#{following_ids})", user_id: id)
end

# Follows a user.
def follow(other_user)
  active_relationships.create(followed_id: other_user.id)
end

# Unfollows a user.
def unfollow(other_user)
  active_relationships.find_by(followed_id: other_user.id).destroy
end

# Returns true if the current user is following the other user.
def following?(other_user)
  following.include?(other_user)
end

private

  # Converts email to all lower-case.
  def downcase_email
    self.email = email.downcase
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
    before_action :correct_user,   only: [:edit, :update]
    before_action :admin_user,     only: :destroy

    def index
    @users = User.paginate(page: params[:page])
    end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @products = @user.products.paginate(page: params[:page])
    @reviews = @user.reviews.paginate(page: params[:page])
    if logged_in?
    @product  = current_user.products.build
    @review = current_user.reviews.build
    @feed_items = current_user.feed.paginate(page: params[:page])
    @feed_reviews = @product.reviews.paginate(page: params[:page])
  end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
      # Handle a successful save.
    else
      render 'new'
    end
end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
      # Handle a successful update.
    else
      render 'edit'
    end
  end

  def destroy
  User.find(params[:id]).destroy
  flash[:success] = "User deleted"
  redirect_to users_url
  end

  def following
  @title = "Following"
  @user  = User.find(params[:id])
  @users = @user.following.paginate(page: params[:page])
  render 'show_follow'
end

def followers
  @title = "Followers"
  @user  = User.find(params[:id])
  @users = @user.followers.paginate(page: params[:page])
  render 'show_follow'
end

  private

  def user_params
    params.require(:user).permit(:firstname, :lastname, :address, :salutation, :zipcode, :country, :contactnum, :email, :password,
                                 :password_confirmation)
  end

def correct_user
  @user = User.find(params[:id])
  redirect_to(root_url) unless current_user?(@user)
end

def admin_user
  redirect_to(root_url) unless current_user.admin?
end

end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.firstname, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary", id: "followbutton" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<div id="signupandin" class="row">

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.select(:salutation, options_for_select([['Mr', 'Mr'], ['Mrs', "Mrs"],
  ['Ms', 'Ms'],['Master', 'Master']], @user.salutation)) %>

  <%= f.label :firstname %>
  <%= f.text_field :firstname, class: 'form-control' %>

  <%= f.label :lastname %>
  <%= f.text_field :lastname, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :Contact %>
  <%= f.text_field :contactnum, class: 'form-control' %>

  <%= f.label :address %>
  <%= f.text_field :address, class: 'form-control' %>

  <%= f.label :zipcode %>
  <%= f.text_field :zipcode, class: 'form-control' %>

  <%= f.label :country %>
  <%= f.text_field :country, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary", id: "submitbutton" %>
<% end %>

</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn", id: "unfollowbutton" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.firstname, user %>
  <%= pluralize(user.followers.count, "fan") %>
  <% if current_user.admin? && !current_user?(user) %>
  | <%= link_to "delete", user, method: :delete,
                                data: { confirm: "You sure?" } %>
<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit User') %>
<% provide(:button_text, 'Save changes') %>
<h1 id="update">Update Your Profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

app/views/users/home.html.erb
<% provide(:title, "Home") %>

<% if logged_in? %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <%= render 'shared/user_info' %>
        </section>
        <section class="stats">
            <%= render 'shared/stats' %>
        </section>
        <section class="product_form">
            <%= render 'shared/product_form' %>
        </section>
    </aside>
</aside>
<div class="col-md-8">
    <h3>Get Inspired
      <a href="<%= following_user_path(@user) %>">
        <strong id="following" class="stat">
          Fans of <%= @user.following.count %> users' product recommendations
        </strong>
      </a>

    </h3>
    <%= render 'shared/feed' %>
</div>
</div>
<% else %>

<div class="center jumbotron">
<h1 id="main">Groceries.
    <br>
    Exchange Ideas and Tips Now!</h1>

<h2>
    A social sharing community for FMCG products.</h2>

<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary", id: "signup" %>
</div>

<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1 id="users">Browse Users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1 id="signupheader">Sign Up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.firstname) %>
<div class="row">

  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.products.any? %>
      <h1 id="profileheader"><%= @user.firstname %>'s Products (<%= @user.products.count %>)</h1>
        <div class="stats">
      <a href="<%= followers_user_path(@user) %>">
        <strong class="stat">
          <%= @user.followers.count %> fans of <%= @user.firstname %>'s product recommendations
        </strong>
      </a>
    </div>
      <ol class="products">
        <%= render @products %>
      </ol>
      <%= will_paginate @products %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.firstname %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Products:</b> <%= @user.products.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>