config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/create',   to: 'products#new'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :products,          only: [:create, :edit, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :reviews,            only: [:create, :destroy]
  resources :products do
     resources :reviews
 end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :product, presence: true
  validates :user_id, presence: true
  validates :description, presence: true, length: { maximum: 400 }
  validates :brand, presence: true, length: { maximum: 40 }
  validates :category, presence: true, length: { maximum: 40 }
  validates :price, presence: true, length: { maximum: 10 }
  validate  :picture_size

  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :edit ]
  before_action :correct_user,   only: [:destroy, :edit ]


  def new
    @product = Product.new
  end

  def create
    @product = current_user.products.build(product_params)
    if @product.save
      flash[:success] = 'Product created!'
      redirect_to current_user
    else
      @feed_items = []
      render '/user/:id'
    end
  end

  def show
    @user = User.find(params[:id])
    @products = @user.products.paginate(page: params[:page])
    @reviews = @user.reviews.paginate(page: params[:page])
    if logged_in?
    @product = Product.find(params[:id])
    @review = current_user.reviews.build
    @feed_items = current_user.feed.paginate(page: params[:page])
    @feed_reviews = @product.reviews.paginate(page: params[:page])
  end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      flash[:success] = 'Product updated'
      redirect_to current_user
      # Handle a successful update.
    else
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    flash[:success] = 'Product deleted'
    redirect_to request.referrer || root_url
  end

  private

    def product_params
      params.require(:product).permit(:product, :description, :brand, :category, :price, :picture)
    end

    def correct_user
      @user = User.find(params[:id])
      # redirect_to(current_user) unless current_user?(@user)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<li id="product-<%= product.id %>">
  <%= link_to gravatar_for(product.user, size: 50), product.user %>
  <span class="user"><%= link_to product.user.firstname, product.user %></span>
  <span class="description">
  <span class="product"> Product Name: <%= product.product %> </span>
  <span class="product"> Brand: <%= product.brand %> </span>
  <span class="product"> Category: <%= product.category %> </span>
  <span class="product"> Price: SGD$  <%= number_with_precision(product.price, precision: 2) %> </span>
  <span id="description"> Description: <%= product.description %> </span>
    <%= image_tag product.picture.url if product.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(product.created_at) %> ago.
    <% if current_user?(product.user) %>
      <%= link_to "DELETE", product, method: :delete,
                                       data: { confirm: "You sure?" } %>
      <%= link_to "EDIT", edit_product_path(product.id) %>
    <% end %>
    <%= link_to "REVIEWS", product %>
    </span>

</li>

app/views/products/edit.html.erb
<% provide(:title, 'Edit Product') %>
<% provide(:button_text, 'Save changes') %>
<h1 id="productupdate">Update your Product</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/product_form' %>
  </div>
</div>

app/views/products/new.html.erb
<% provide(:title, 'Create') %>
<% provide(:button_text, 'Save changes') %>
<h1 id="createproduct">Create a New Product</h1>


<div id="productform">
<%= form_for(@product, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">

    <%= f.label :product %>
    <%= f.text_field :product, class: 'form-control' %>

    <%= f.label :brand %>
    <%= f.text_field :brand, class: 'form-control' %>

    <%= f.label :category %>
    <%= f.text_field :category, class: 'form-control' %>

    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control' %>

    <%= f.text_area :description, placeholder: "Share your tips!" %>

  </div>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>

  <%= f.submit "Post", class: "btn btn-primary", id: "loginbtn" %>

</div>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/products/show.html.erb
<% provide(:title, 'Product') %>

<h1 id="productview">Product</h1>

<ol class="products">
<%= render @product %>

<%= form_for([@review.product_id, @review]) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

<h5 id="reviewtitle"> Reviews (<%= @product.reviews.count %>) </h5>

<ol class="products">
  <%= render @product.reviews %>
</ol>
<%= will_paginate @reviews %>

  <div id="reviewform" class="field">
    <h5> Write your review </h5>
    <%= f.hidden_field :product_id, :value => @product.id  %>
    <%= f.text_area :content, placeholder: "Don't be shy..." %>
      <%= f.submit "Share your review", class: "btn btn-primary", id: "loginbtn" %>
  </div>

<% end %>