config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/create',   to: 'products#new'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :products,          only: [:create, :edit, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :reviews,            only: [:create, :destroy]
  resources :products do
     resources :reviews
 end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small> Gerald Ang </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header id="topheader" class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to image_tag("redmart-logo.png", alt: "Redmart logo", :style => "height: 40px; margin-top: 0%; margin-bottom: -4%;"),
        root_path %>
        <nav>
            <ul id="headerlinks" class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                <li><%= link_to "Get Inspired", root_path %></li>
                <li><%= link_to "Your Products", current_user %></li>
                <li><%= link_to "Create A Product", create_path %></li>
                <li><%= link_to "Browse Users", users_path %></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Account
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Profile", current_user %></li>
                        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                        <li class="divider"></li>
                        <li>
                            <%= link_to "Log out", logout_path, method: "delete" %>
                        </li>
                    </ul>
                </li>
            <% else %>
                <li><%= link_to "LOG IN", login_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= yield(:title) %>
            | Redmart</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
        <%= render 'layouts/shim' %>

        <!--[if lt IE 9]> <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"> </script> <![endif]-->
    </head>
    <body>
        <header class="navbar navbar-fixed-top navbar-inverse">
            <%= render 'layouts/header' %>
            <div class="container">
                <%= link_to "sample app", 'root_path', id: "logo" %>
                <nav>
                    <ul class="nav navbar-nav navbar-right">
                        <li><%= link_to "Home",   'root_path' %></li>
                        <li><%= link_to "Help",   'help_path' %></li>
                        <li><%= link_to "Log in", '#' %></li>
                    </ul>
                </nav>
            </div>
        </header>

        <div class="container">
            <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
            <%= yield %>
            <%= render 'layouts/footer' %>
            <%= debug(params) if Rails.env.development? %>
        </div>
    </body>
</html>